### ISSUE TITLE
Questions on the mutliverse of versions

### ISSUE THREAD

**Issue by v1gnesh** [wader/bump#109]
Hello, our paths cross again :)

I'm pretty new to this proj (only saw it yesterday), and as I try to understand it... it will be super helpful if you can show some examples of how to use this to keep references to tarball sources updated.

My use case is to keep ports up-to-date at https://github.com/ZOSOpenTools/.
Git covers a fair chunk of sources, but there are GNU sources and such, where we need to fetch from tar.gz and so on.
Example: https://github.com/ZOSOpenTools/gitport/blob/main/buildenv or https://github.com/ZOSOpenTools/opensshport/blob/main/buildenv

Any guidance will be of huge help, as I'm sure the tool will be.

✌️

**Comment by wader** [comment]
> Hello, our paths cross again :)

Hey! 👋 

> I'm pretty new to this proj (only saw it yesterday), and as I try to understand it... it will be super helpful if you can show some examples of how to use this to keep references to tarball sources updated.
> 
> My use case is to keep ports up-to-date at https://github.com/ZOSOpenTools/. Git covers a fair chunk of sources, but there are GNU sources and such, where we need to fetch from tar.gz and so on. Example: https://github.com/ZOSOpenTools/gitport/blob/main/buildenv or https://github.com/ZOSOpenTools/opensshport/blob/main/buildenv
> 
> Any guidance will be of huge help, as I'm sure the tool will be.

Sure, for example the gitport could do something like this:
```diff
diff --git a/buildenv b/buildenv
index ebfc813..ab5dc91 100644
--- a/buildenv
+++ b/buildenv
@@ -3,6 +3,7 @@
 #
 export ZOPEN_TYPE="TARBALL"

+# bump: git /GIT_VERSION="(.*)"/ https://github.com/git/git.git|*
 GIT_VERSION="2.41.0"

 export ZOPEN_GIT_URL="https://github.com/git/git"
```
Here "git" is the name of the thing tracked, `GIT_VERSION="(.*)"` a regex to find current version and `https://github.com/git/git.git|*` a "pipeline" to fetch versions from some source and filter them to get a latest suitable one, this uses git tags from `https://github.com/git/git.git` and then `*` is short for `semver:*` (higest semver version), could be `^2` etc also.

Add a new file `Bumpfile` with a list of files (or bump config) that bump should concider, so just `buildenv` is this case. You can also skip the `Bumpfile` and provide a path as CLI argument or github action option.

There are some instructions in the README.md how to setup github action https://github.com/wader/bump#github-action

Will be out on bike vacation the next week (but will bring laptop :)) so might be a bit slow to answer.

**Comment by v1gnesh** [comment]
Thank you, I'll give it a go.
Have fun!

**Comment by v1gnesh** [comment]
Hey, it's actually for the whole lot under https://github.com/ZOSOpenTools.
I'm pretty slow, so will take a bit for me to get my head around it lol.
But will report back here for sure.

**Comment by wader** [comment]
Ok no worries! just ask if you have any questions.

Nicest is usually do use a source repo as source of versions, ex in this case you could use:
```sh
# bump pipeline is a command to run pipelines, add -v if you want to see more verbose output
$ bump pipeline 'https://git.savannah.gnu.org/git/autoconf.git|*'
2.71
```
Note that from time to time developers tag versions very early which might trigger bump to find a versions that has not been released yet. But it's quiet rare.

If that was not the case in these was only list listing i guess you would have to use "fetch" and then some regexp magic to match for versions which is not nice... but works. So advice is try use git, svn, depsdev etc as versions source.

**Comment by v1gnesh** [comment]
@wader, I've set `GIT_VERSION` back to 2.40.0 in the `buildenv`, and the above git example works.

```shell
m1ni@m1ni /Users/m1ni/zopen/gitport % bump -v check buildenv
buildenv:7: git 2.40.0 -> 2.41.0 1.221s
m1ni@m1ni /Users/m1ni/zopen/gitport % bump check buildenv 
git 2.41.0
m1ni@m1ni /Users/m1ni/zopen/gitport % bump diff buildenv 
--- buildenv
+++ buildenv
@@ -4,7 +4,7 @@
 export ZOPEN_TYPE="TARBALL"
 
 # bump: git /GIT_VERSION="(.*)"/ https://github.com/git/git.git|*
-GIT_VERSION="2.40.0"
+GIT_VERSION="2.41.0"
```
However, when I try zstd, it doesn't :(

```shell

# bump: zstd-tar-version /TARBALL_VERSION=v"(.*)"/ https://github.com/facebook/zstd.git|*
TARBALL_VERSION=v1.5.2

export ZOPEN_TARBALL_URL="https://github.com/facebook/zstd/archive/refs/tags/${TARBALL_VERSION}.tar.gz"
```


```shell
m1ni@m1ni /Users/m1ni/zopen/zstdport % bump check buildenv 
buildenv:6: zstd-tar-version has no current version matches
m1ni@m1ni /Users/m1ni/zopen/zstdport % bump pipeline "https://github.com/facebook/zstd.git|semver:*"
1.5.5
```

**Comment by v1gnesh** [comment]
Hey, how would I look up v3r17 from git tags for example?
https://github.com/zigi/zigi/tags

**Comment by wader** [comment]
> @wader, editing this comment to say it works 👍 Will try for the different variety of URLs I have.

👍 great, saw in notification email :) problem with the regex and the "v"? was the error message confusing or something that could be improved to make it clearer?

**Comment by wader** [comment]
> Hey, how would I look up v3r17 from git tags for example? https://github.com/zigi/zigi/tags

Interesting, so v3r17 could be seen as 3.17? something like this:
```sh
$ bump pipeline 'gitrefs:https://github.com/zigi/zigi.git|re:/v(\d+)r(\d+)/$1.$2/|*'
3.17
```

This uses `gitrefs` source which is like `git` but i does not have any magic to find versions, you just get the raw refs, then uses a regex to match out the to numbers and construct at number1.number2 string and last semver latest.

**Comment by wader** [comment]
btw if you just want to try things there is a "static" source so you can do:
```sh
$ bump pipeline 'static:v3r17,v2r23|/v(.*)r(.*)/$1.$2/'
3.17
```

**Comment by v1gnesh** [comment]
> problem with the regex and the "v"? was the error message confusing or something that could be improved to make it clearer?

User error 😛 I put quotes in the bump text when the line of interest didn't have any.

```
bump: zstd-tar-version /TARBALL_VERSION=v"(.*)"/ https://github.com/facebook/zstd.git|*
TARBALL_VERSION=v1.5.2
```

**Comment by v1gnesh** [comment]
Hey, I wonder... do you think there's value in there being a bumperbot?
An alternative to dependabot that runs bump with all the power of bump 🦾

**Comment by wader** [comment]
Benefit would be that it could run for a whole organisation or user etc without much setup? i haven't looked into how github apps work (i think that is what dependabot is?) so no idea how much work it would be.

I guess one "problem" would be that is has to run somewhere if i understand how i works? looks like it's hooks and API:s compare to github action which runs code? maybe one can mix somehow?

**Comment by v1gnesh** [comment]
> Benefit would be that it could run for a whole organisation or user etc without much setup?

Yup..

> I haven't looked into how github apps work (i think that is what dependabot is?)

Probably..

> I guess one "problem" would be that is has to run somewhere if i understand how i works? looks like it's hooks and API:s compare to github action which runs code? maybe one can mix somehow?

Earlier today, I saw that Dependabot can be setup to trigger GitHub Actions, so there's a place for both.
I'm no expert in either, so just thinking out loud, to find the simplest way to bump version that are in buildenv files, across 100+ repositories.

**Comment by wader** [comment]
> Earlier today, I saw that Dependabot can be setup to trigger GitHub Actions, so there's a place for both. I'm no expert in either, so just thinking out loud, to find the simplest way to bump version that are in buildenv files, across 100+ repositories.

I see, hmm will think about it. Would guess it's quite a bit of work

**Comment by v1gnesh** [comment]
Is it ok that I ask about edge cases here, I've got 100+ repos to go through 😅 
How would you suggest I parse for sudo?
https://www.sudo.ws/dist/

This gets 1.9.13, but the optional p<n> trips the final semver:

`https://www.sudo.ws/dist/|re:/sudo-(\d+\.\d+\.\d*\d).tar.gz/|semver:*`

`sudoport/buildenv:4: sudo-version 1.9.13p3 -> 1.9.13 1.184s`

**Comment by wader** [comment]
> Is it ok that I ask about edge cases here, I've got 100+ repos to go through 😅 

No worries :) i just can't promise anything. I wonder if in your case you could do some custom with a shell script that runs with a token with lots of access and then use github cli command to iterate all repos and run bump somehow?

> How would you suggest I parse for sudo? https://www.sudo.ws/dist/
> 
> This gets 1.9.13, but the optional p trips the final semver:
> 
> `https://www.sudo.ws/dist/|re:/sudo-(\d+\.\d+\.\d*\d).tar.gz/|semver:*`
>
> `sudoport/buildenv:4: sudo-version 1.9.13p3 -> 1.9.13 1.184s`

Yeah that is problem, semver is quite strict and sadly "extra" thing after the version is seen as pre release so i sorted that way :(

I wonder in this case if some kind of natural or "version" sort filter would be needed?
 
> And sqlite.
> 
> https://sqlite.org/2023/sqlite-autoconf-3420000.tar.gz from https://sqlite.org/download.html
> 
> Why can't everyone use one standard lol.

i guess bump kind of exist partly because it is a mess 😬 

Something like this?

```sh
$ bump pipeline 'gitrefs:https://github.com/sqlite/sqlite.git|/version-(.*)/$1/|*'
3.42.0
```

But maybe does not match version in download URL?

I've had some ideas that "next-generation" bump if ever happens should probably use some more expressive pipeline language like jq.

**Comment by v1gnesh** [comment]
> No worries :) i just can't promise anything.

Absolutely, I'm hoping the edge cases will help find some ideas for tackling more things in the next-gen bump.

> I wonder if in your case you could do some custom with a shell script that runs with a token with lots of access and then use github cli command to iterate all repos and run bump somehow?

I have the following in mind:
zpull - clone or pull all *port repos under github.com/zosopentools
zbump - Use the Bumpfile to run bump check -v, bump diff, bump update
zpush - Recurse through zopen's sub-dirs and look for git dirs where git diff is 'dirty', then commit buildenv & create a patch for it

Collect all patches and send it over, because I don't have rights on most of the repos.
100+ PRs is wild. I tried `gh pr create` but it seems to want me to fork the repo.

```
├── zopen
│   ├── Bumpfile
│   ├── autoconfport
│   ├── automakeport
│   ├── ...
│   ├── zbump.sh
│   ├── zpull.sh
│   ├── zpush.sh
│   ├── zsshr.sh
```

https://github.com/linux-on-ibm-z/dockerfile-examples
Look at this beauty, and (after an initial regex setup time) imagine how much time bump can save.


Background: I'm a mainframer. There are 2 predominant mainframe OS-es.
The buildenv stuff is related to porting stuff to zOS.
This linux-on-ibm-z repo is related to the second OS - Linux on Z.

> I wonder in this case if some kind of natural or "version" sort filter would be needed?

Yup.



I made a silly error in the regex for picking the 'current version' in the Bumpfile.
Now it works!

```shell
sqliteport/buildenv:3: sqlite-year 2023 -> 2023 2.854s
sqliteport/buildenv:4: sqlite-version 3420000 -> 342000 2.780s
```

**Comment by wader** [comment]
> > No worries :) i just can't promise anything.
> 
> Absolutely, I'm hoping the edge cases will help find some ideas for tackling more things in the next-gen bump.

👍 

> > I wonder if in your case you could do some custom with a shell script that runs with a token with lots of access and then use github cli command to iterate all repos and run bump somehow?
> 
> I have the following in mind: zpull - clone or pull all *port repos under github.com/zosopentools zbump - Use the Bumpfile to run bump check -v, bump diff, bump update zpush - Recurse through zopen's sub-dirs and look for git dirs where git diff is 'dirty', then commit buildenv & create a patch for it
> 
> Collect all patches and send it over, because I don't have rights on most of the repos. 100+ PRs is wild. I tried `gh pr create` but it seems to want me to fork the repo.
> 
> ```
> ├── zopen
> │   ├── Bumpfile
> │   ├── autoconfport
> │   ├── automakeport
> │   ├── ...
> │   ├── zbump.sh
> │   ├── zpull.sh
> │   ├── zpush.sh
> │   ├── zsshr.sh
> ```

Yeap something like that might be good workaround for now, might be some work but probably nice to have it in one place at least.

BTW you can put bump config in any file if you don't want to have a Bumpfile, then just do `bump update <file>`.

> https://github.com/linux-on-ibm-z/dockerfile-examples Look at this beauty, and (after an initial regex setup time) imagine how much time bump can save.

What should i be looking at? 👀  looked for bump config but found none :)

Yeap bump have saved me tons of time and also saved time when you find incompatibilities fast.

> Background: I'm a mainframer. There are 2 predominant mainframe OS-es. The buildenv stuff is related to porting stuff to zOS. This linux-on-ibm-z repo is related to the second OS - Linux on Z.

I see, so professional mainframer? maybe that is the only kind? :)

> > I wonder in this case if some kind of natural or "version" sort filter would be needed?
> 
> Yup.

Will try add something, thinking maybe the `sort` filter can take options so for example `sort:version` would do "version sort" and just `sort` alphabetical... and in both cases it's also reverse to get "highest".

> I made a silly error in the regex for picking the 'current version' in the Bumpfile. Now it works!
> 
> ```shell
> sqliteport/buildenv:3: sqlite-year 2023 -> 2023 2.854s
> sqliteport/buildenv:4: sqlite-version 3420000 -> 342000 2.780s
> ```

Been there :)

**Comment by v1gnesh** [comment]
>> https://github.com/linux-on-ibm-z/dockerfile-examples
>> Look at this beauty, and (after an initial regex setup time) imagine how much time bump can save.

> What should i be looking at? 👀 looked for bump config but found none :)

Haha, at the possibility... of bump giving back the maintainer's time 😁 

> I see, so professional mainframer? **maybe that is the only kind? :)**

Actually yeah; the only available personal emulated version of zOS costs ~$5k/yr.
There was a much cheaper version, but that was yanked pretty soon, and the question of whether it'll return is still in the air (a year or more later).

> Will try add something, thinking maybe the sort filter can take options so for example sort:version would do "version sort" and just sort alphabetical... and in both cases it's also reverse to get "highest".

When working out openssl yesterday, for 1.x.x(char), this picks up the trailing char too.
`https://www.openssl.org/source/|re:/openssl-(\d\.\d\.\d)(\w)/$1$2/`

Doesn't work for sudo 1.9.13p3 (which has number after the char 'p').
Have a work-around for now.

For feature requests - having a `bump version-history` to see the versions bump would have picked in reverse chronological order is useful to confirm the regex works ok over time. This'll be more reassuring than seeing the current version alone being picked right.

**Comment by v1gnesh** [comment]
> Did you managed to get bump to sort those versions in a usable way? btw the the last char optional maybe?

Yeah, the pipeline I shared works. Don't know about the optional char part... it has had it for a while now.
Anyway, we're moving to OpenSSL v3 soon (v1 going out of support in September); so not bothered too much.

> How does the workaround work? 😄

I'm using this for getting 1.9.13. Then 'p3' is hard-coded lol.
`https://www.sudo.ws/dist/|re:/sudo-(\d+\.\d+\.\d+).tar.gz/|semver:*`

On version sort, yeah sure, can try it out.

Yeah the versions it picks shows up in pipeline -v, but it's too verbose as you say; mainly because of the HTML page print.
Just thought of a better name for version-history -- `bump backtest`!

**Comment by wader** [comment]
> > Did you managed to get bump to sort those versions in a usable way? btw the the last char optional maybe?
> 
> Yeah, the pipeline I shared works. Don't know about the optional char part... it has had it for a while now. Anyway, we're moving to OpenSSL v3 soon (v1 going out of support in September); so not bothered too much.
> 
> > How does the workaround work? 😄
> 
> I'm using this for getting 1.9.13. Then 'p3' is hard-coded lol. `https://www.sudo.ws/dist/|re:/sudo-(\d+\.\d+\.\d+).tar.gz/|semver:*`
> 
> On version sort, yeah sure, can try it out.

Have a look at https://github.com/wader/bump/pull/112 if you have golang installed you can run it like this:
```sh
$ go run github.com/wader/bump/cmd/bump@version-sort pipeline 'gitrefs:https://github.com/sudo-project/sudo.git|/SUDO_(.*)/$1/|sort:version'
1_9_13p3
```

Still a rough draft but seems to work quite well

> 
> Yeah the versions it picks shows up in pipeline -v, but it's too verbose as you say; mainly because of the HTML page print. Just thought of a better name for version-history -- `bump backtest`!

**Comment by v1gnesh** [comment]
> How about just bump versions NAME? i guess it only make sense to run specifying a NAME?

Yup, sounds good.
Could it be the original dot, rather than underscore - 1.9.13p3.
sudo, openssl, don't know (off the top of my head) of other packages that have versions like this.
There are some like 1.4.6a3 though..

**Comment by wader** [comment]
Impressive! how long does it take to run?

Yes @latest will end up building the master branch where the sort filter is probably not happy about getting an argument "version". Haven't had much time looking into what to do about more flexible/configureable version sort. Any ideas how it could look like?

Nice trick with `**/buildenv` :) btw in zbump.sh i see:
```
# Make the updates
bump update
````
Should it be `bump update **/buildenv` also?

**Comment by v1gnesh** [comment]
> Impressive! how long does it take to run?

Think about 5s. Some of it I'm sure is down to some quirky domains.

> Should it be bump update **/buildenv also?

Whoops, yup.

> flexible/configureable version sort. Any ideas how it could look like?


Was looking through the sudo.ws site and [this page](https://www.sudo.ws/getting/source/) is pretty neat - 

```shell
$ bump pipeline -v 'https://www.sudo.ws/getting/source/|re:/sudo-([\d.]+p?\d?).tar.gz"/$1/

  @ name -> name
re:/sudo-([\d.]+p?\d?).tar.gz"/$1/:
  1.9.14
  1.9.13p3
  1.9.13p2

```

Whereas [this page](https://www.sudo.ws/dist/) trips on it, and shows `1.8.0`.
I guess it helps to have the source html display versions in sorted order.

**Comment by wader** [comment]
> > Impressive! how long does it take to run?
> 
> Think about 5s. Some of it I'm sure is down to some quirky domains.

👍  bump will currently do all pipelines in parallell so given enough bandwidth it should more or less take as long as the slowest

> > flexible/configureable version sort. Any ideas how it could look like?
> 
> Was looking through the sudo.ws site and [this page](https://www.sudo.ws/getting/source/) is pretty neat -
> 
> ```shell
> $ bump pipeline -v 'https://www.sudo.ws/getting/source/|re:/sudo-([\d.]+p?\d?).tar.gz"/$1/
> 
>   @ name -> name
> re:/sudo-([\d.]+p?\d?).tar.gz"/$1/:
>   1.9.14
>   1.9.13p3
>   1.9.13p2
> ```
> 
> Whereas [this page](https://www.sudo.ws/dist/) trips on it, and shows `1.8.0`. I guess it helps to have the source html display versions in sorted order.

Aha you rely on the order in the page, that works.

I have some vague idea that the sort filter could be told how to sort per "column", made up example: `sort:<.<.<.?<`, column 1,2,3 prefer higher, column 4 prefer empty otherwise higher, but haven't given it much thought.

**Comment by v1gnesh** [comment]
No worries, I'm happy that bump even exists and has got us to the other side.
This could be revisited if more people come across non-semver stuff.

**Comment by wader** [comment]
Yeap let's keep the issue open and see

Happy to hear it's being useful! 🥳

**Comment by v1gnesh** [comment]
Hey @wader, reporting back to say all good.
Looking to set up GH Action(s) for the org, starting with one repo.

**Comment by wader** [comment]
@v1gnesh Nice to hear! 👍 would be nice to have a peek at the setup once it's up! and as always just give me a shout if there is anything

**Comment by v1gnesh** [comment]
It sez `bumpfile (INPUT_BUMPFILE) is empty`.
When you have time, could you check what's missing. 
I have embedded commands in `buildenv`.

https://github.com/ZOSOpenTools/duckdbport/actions/runs/6199894436/job/16833401842

**Comment by wader** [comment]
Yeap will have look when i have time. But the link gives me 404 not found hmm

**Comment by v1gnesh** [comment]
Ah sorry, it'll be in https://github.com/ZOSOpenTools/duckdbport/actions.

**Comment by wader** [comment]
Try add `bumpfile` to https://github.com/ZOSOpenTools/duckdbport/blob/main/action/action.yml (same as https://github.com/wader/bump/blob/master/action/action.yml#L11-L14) and rename `files` to `bump_files`.

But i have feeling i might have messed up in https://github.com/wader/bump/commit/7e394457914f7b576b5b3cbc3c127e394393116e when i renamed "bump_files" to "files, in the commit message it says `github action input "bump_files" is now called "files".
` so maybe i should fix that.

**Comment by v1gnesh** [comment]
Woohoo, it works! It needs `bump_files` indeed.

**Comment by wader** [comment]
> Woohoo, it works! It needs `bump_files` indeed.

🥳 

> Need to figure out triggering builds based on PR next.

I had to use a PAT-token to do this i think? but maybe things has changed? there is some notes about it at https://github.com/wader/bump#github-action

> Do you know of any Action that will allow doing stuff to an SSH target? There isn't a supported GH Actions runner for the `s390x` platform it should build for.

You mean something like https://github.com/owenthereal/action-upterm but i haven't used it myself

Or did you mean something bump-related don't run on s390x?

**Comment by v1gnesh** [comment]
Your notes saved me hours of reading for sure :stuck_out_tongue: 
Bump works great on s390x.

An extension of sorts that will let Actions do stuff to an SSH target... if one exists... will be great.
Maybe I should look into SSH-ing from the Actions runner (ubuntu-latest for example) into my s390x target, do stuff there, and report back to the runner.
Currently, builds are scheduled on Jenkins linux/s390x, and they're _run_ on zos/s390x.

**Comment by wader** [comment]
> Your notes saved me hours of reading for sure 😛 Bump works great on s390x.

👍 

> An extension of sorts that will let Actions do stuff to an SSH target... if one exists... will be great. Maybe I should look into SSH-ing from the Actions runner (ubuntu-latest for example) into my s390x target, do stuff there, and report back to the runner. Currently, builds are scheduled on Jenkins linux/s390x, and they're _run_ on zos/s390x.

Aha you want to ssh out from the runner, thought you wanted to debug on the runner :) i guess you should be abele to "just" ssh somewhere? but i maybe biggest mess i handling of keys etc?

**Comment by v1gnesh** [comment]
Yeah.. keys, getting command outputs back, reporting that back to GH, etc.
So much so that I'm wondering if it's possible to build buildkite's agent for the platform.
That'll sort all of this out.

**Comment by wader** [comment]
You mean implement a "self-hosted runners" thingy? yeah that would nice i guess

**Comment by v1gnesh** [comment]
Yup
