### ISSUE TITLE
Partial semver

### ISSUE THREAD

**Issue by v1gnesh** [wader/bump#127]
Hello again!

It seems that vim pushes a tag for each commit (or something close).
I can use this from the command line to get just `v.r`.
Is there a cleverer way to do this with `semver:` keywords?

`bp` is an alias to `bump pipeline`.

```shell
 bp 'https://github.com/vim/vim.git|semver:*|n.n'
7.0
 bp 'https://github.com/vim/vim.git|semver:*|re:/([\d]+).([\d]+).([\d]+)/$1-$2-$3/'
9-0-2127
 bp 'https://github.com/vim/vim.git|semver:*|re:/([\d]+).([\d]+).([\d]+)/$1.$2/'
9.0
```

**Comment by wader** [comment]
Hey, if i understand you correctly with #130 merged you now get this:
```sh
$ bump pipeline 'https://github.com/vim/vim.git|semver:*|semver:n'
9
$ bump pipeline 'https://github.com/vim/vim.git|semver:*|n.n'
9.0
$ bump pipeline 'https://github.com/vim/vim.git|semver:*|n.n.n'
9.0.2127
$ bump pipeline 'https://github.com/vim/vim.git|semver:^8|n.n'
8.2
```

Problem was that semver filter in template mode wrongly sorted versions which it shouldn't, it should just use the first version it gets.

**Comment by v1gnesh** [comment]
Awesome, thank you!
Any suggestion on how to deal with vim in particular.
Would be nice for this to show up once in a while - 9.0.2100, 9.0.2200, etc.

https://github.com/ZOSOpenTools/vimport/pulls?q=is%3Apr+is%3Aclosed+update+vim-version

**Comment by wader** [comment]
Aha now i see, you want to only update every N-version etc? not pretty but for every 100 maybe something like `https://github.com/vim/vim.git|semver:*|n.n.n|/\d00$/`?

**Comment by v1gnesh** [comment]
Awesome again, that works! :heart: 
Yeah, vim pushes these out way too frequently.

**Comment by wader** [comment]
👍  but i did noticed a bug or annoying thing with the current pipeline parser if one wants to use ex. `...|re:/\.(0|\d+00)$/` as regexp. there is no way to escape the `|` in the regexp so it will end up seen as a filter separator :( i should probably fix that somehow. It's amazaing how many bugs you find when you don't work on some projects and then come back again :)

**Comment by v1gnesh** [comment]
@wader On the surface, this looks funny - https://github.com/ZOSOpenTools/vimport/pull/45
Do you know if, after merging this PR, it'll compare the "existing" 2100 to a new 2200 that will show up in the future?

**Comment by wader** [comment]
:) yes current version found using the regexp is compared to whatever the pipeline outputs as first value. If they are not equal string-wise the value is updated. Does that make sense and clarify things?

**Comment by v1gnesh** [comment]
Yup, thanks again!
