### ISSUE TITLE
Question: how to define docker label with versions?

### ISSUE THREAD

**Issue by szymonsasin-nordic** [wader/bump#93]
I'm looking at docker images from https://hub.docker.com/_/amazoncorretto, there label contains two versions, one for jvm and another for alpine. How to define Bumpfile, so that this version: `amazoncorretto:17.0.4-alpine3.15` would be updated to this one: `amazoncorretto:17.0.5-alpine3.16`?

**Comment by wader** [comment]
Hey, if you want to only sort on the first version number you could do something like:
```
$ bump pipeline 'docker:amazoncorretto|/^([\d.]+)-alpine.*/|^17'
17.0.5
```
Or replace ^17 with * for highest major (19.0.1)

To sort based on both corretto and alpine version i think is a bit tricky at the moment, ill think about it. A workaround could be to have two different configs for the versions, the one above and then one:
```
$ bump pipeline 'docker:amazoncorretto|/.*-alpine([\d.]+)/|*'
3.16
```
but it could technically end up with a tag that don't exist.

btw you can run with -v if you want to see filter pipeline debug.

hope that helps!

**Comment by szymonsasin-nordic** [comment]
Hi, thanks for quick answer.

With two pipelines, how can I then combine them into single docker label?

**Comment by wader** [comment]
Not pretty but something like this:
```
# bump: amazoncorretto-corretto /FROM amazoncorretto:([\d.]+)-alpine.*/ docker:amazoncorretto|/^([\d.]+)-alpine.*/|^17
# bump: amazoncorretto-alpine /FROM amazoncorretto:.*-alpine([\d.]+)/ docker:amazoncorretto|/.*-alpine([\d.]+)/|*
FROM amazoncorretto:17.0.4-alpine3.15
```
Seems to work:
```
$ bump check -v test
test:10: amazoncorretto-corretto 17.0.4 -> 17.0.5 1.170s
test:10: amazoncorretto-alpine 3.15 -> 3.16 1.182s
```

**Comment by szymonsasin-nordic** [comment]
Awesome, thanks.

**Comment by wader** [comment]
👍  I should probably add this to some kind of FAQ
